### ISSUE TITLE
Npm version and github version

### ISSUE THREAD

**Issue by kompot** [wix/redux-saga-tester#1]
Hi,
I really like this package guys and wonder why repository version is 1.0.1 and NPM already has 1.0.17?

Wanted to fork and remove optional dependency to `@wix/wnpm-ci` that causes `yarn`
https://github.com/yarnpkg/yarn
to fail when performing install.

**Comment by 3LOK** [comment]
Hi,

I fixed the reason why yarn isn't working (the optionalDependency), and published. 

This should now have redux-saga-tester working with yarn.

As for your package.json question, it's a bug with our CI system that doesn't update the package.json when releasing (but update it prior to releasing). We will work on solving it, but it shouldn't have any affect on you in general.

Thanks!

 - Yoav.

**Comment by kompot** [comment]
Great, thanks.
* now `yarn` fails on another optional dep, yikes *

But is there any reason `redux-saga-tester` version in `package.json` is 1.0.1 and npm published version is 1.0.19?

**Comment by 3LOK** [comment]
Hi,

You wrote ```now yarn fails on another optional dep, yikes```. What do you mean?

Here's my result of installing redux-saga-tester with yarn:

```bash
Yoavs-MacBook-Pro-4:aaa trilok$ yarn add redux-saga-tester
yarn add v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency
└─ redux-saga-tester@1.0.19
✨  Done in 3.73s.
```

so it seems ok on my side,

**Comment by kompot** [comment]
Sorry for confusion — I was referring to another project that my project depends on that also had an optional dependency.
So everything's ok with redux-saga-tester, thanks.

**Comment by 3LOK** [comment]
Ah, ok, perfect! :) Got me worried there :)
