### ISSUE TITLE
waitFor a sequence of actions

### ISSUE THREAD

**Issue by eliseumds** [wix/redux-saga-tester#11]
Hi everyone! Is there a way to listen for a sequence of actions? My saga does the following:

* Takes action *UPLOAD_ALL*
* Selects the list of objects to be uploaded from the Redux store
* Immediately dispatches `startUpload` for each of them

In my tests, I have two objects that should start uploading one after the other:

```js
sagaTester.dispatch(initialize('myUploader', { objects: [{ id: 'a' }, { id: 'b' }] }));
sagaTester.dispatch(uploadAll('myUploader');

await sagaTester.waitFor(START_UPLOAD);
// here, ideally, only object "a" would have the flag `isUploading=true`

await sagaTester.waitFor(START_UPLOAD);
assert(getObjects().every(object => object.isUploading));
```

Basically the `waitFor` would listen to a single event. We could also think of some other ways to match an event:

```js
await sagaTester.waitFor('@@myLib/*');
await sagaTester.waitFor([ACTION_A, ACTION_B]);
await sagaTester.waitFor(SOME_ACTION, action => action.payload.progress > 20);
```

Thanks!

**Comment by 3LOK** [comment]
Hi @eliseumds,

These are some excellent points.

I've added an example [here](https://github.com/wix/redux-saga-tester/blob/master/examples/example.multiple.waitfor.js) for waiting for multiple instances of the same action. In the example you'll be able to see two scenarios - one where the actions are sent 'immediately' one after the other (with no 'context-switch', for a lack of a better word, between them), and one with a 'context-switch' between each ```yield put```. 

This is of course problematic, as your tests should be affected by the way whether there is, or isn't, a 'context switch'.

I will put some thoughts into implementing a way to join these two cases so their tests will be similar.

As for your second note, about having smarter 'waitFor's, I think these are some excellent ideas. We will definitely look into implementing these.

Thanks.

**Comment by Fzzr** [comment]
I also would love the smarter `waitFor`s, particularly the array one. My use case looks something like `await sagaTester.waitFor([SUCCESS_ACTION, FAIL_ACTION]);`.

**Comment by 3LOK** [comment]
I'm leaving this issue open - if someone wants to give a PR, I'll be happy to merge.

@Fzzr theoretically you could do:
await Promise.race([sagaTester.waitFor(SUCCESS_ACTION), sagaTester.waitFor(FAIL_ACTION)])

**Comment by Fzzr** [comment]
Thanks @3LOK. We went with more granular tests, obviating the need to wait for multiple actions. That was probably the right thing to do, in the end.

**Comment by 3LOK** [comment]
Ok, thanks - so closing.
