### ISSUE TITLE
wasCalled always returns true if waitFor was called before it

### ISSUE THREAD

**Issue by TehBigA** [wix/redux-saga-tester#16]
`waitFor` pushes an Object keyed by the action type into `actionLookups` and since `wasCalled` only checks if the action type was in `actionLookups` it returns true every time.

I think `wasCalled` should be similar to numCalled:
```js
    wasCalled(actionType) {
        const action = this.actionLookups[actionType];
        return action && action.count > 0;
    }
```

**Comment by 3LOK** [comment]
[Fixed!](https://github.com/wix/redux-saga-tester/commit/509fca8a9cfbb3c2f08db024d97bd38690f886c4)
Better late than never I guess... :(
