### ISSUE TITLE
yield select(...) seems to stop the saga tester from executing

### ISSUE THREAD

**Issue by TehBigA** [wix/redux-saga-tester#20]
I recently added auth to my application and I use the following to fetch the auth information to pass into API calls within my sagas:
```js
const auth = yield select(makeSelectAuth());
```

I debugged the tests and noticed my selector was called and returning my mocked data, but then the next yield never calls. I can't figure out if this is a fault of the tester or my own. Any help is appreciated.

**Comment by outofambit** [comment]
I'm pretty sure I am seeing the same behavior in my own experiments to integrate this into our saga testing. @TehBigA have you had any breakthroughs on this issue, by any chance?

**Comment by erikvold** [comment]
> const auth = yield select(makeSelectAuth());

are you sure that you want `select` ? usually you would pass a function to select does `makeSelectAuth()` return a function? it looks you might want

    const auth = yield put(makeSelectAuth());

**Comment by outofambit** [comment]
@erikvold thanks so much for the response! i took another look at my saga and realized that i was running the saga incorrectly and as a result my initial dispatch to the saga didn't trigger anything. 😒 i'm fine with closing this issue!

**Comment by 3LOK** [comment]
Closing the issue.

Indeed it seems you've been using select incorrectly (the parameter should be a function). It should probably be:
```
const auth = yield select(makeSelectAuth);
```
Or, as @erikvold suggested, some other side effect such as ```put```.
