### ISSUE TITLE
Not working with immutable.js if used without a reducer

### ISSUE THREAD

**Issue by JonathanStoye** [wix/redux-saga-tester#31]
If you are using [immutable.js](https://github.com/facebook/immutable-js) and do not pass a reducer to the constructer you will run into the same issue like I did today.

Because `Object.assign` is [used](https://github.com/wix/redux-saga-tester/blob/master/src/SagaTester.js#L36) in case no reducer exists your state will look like an immutable value in the console even though at this point it is none anymore when `sagaTester.getState()` is called.

My workaround for now was to just always pass at least a root reducer which just passes the state.

```
const sagaTester = new SagaTester({
    initialState,
    reducers: function rootReducer(state) {
      return state;
    },
  });
```

Would be either nice to have that in the docs or add a version that supports immutable.js. If you agree I can create a PR.

Thx for this nice piece of code btw! ❤️

**Comment by CarlosLanderas** [comment]
Having the same trouble using ImmutableJS

**Comment by 3LOK** [comment]
@JonathanStoye  - 
Three months late on a reply :( I'm a bad maintainer - but I'll try to improve.
PR would be great!

**Comment by JonathanStoye** [comment]
@3LOK now I have been late 😁 
What about https://github.com/wix/redux-saga-tester/pull/48?

**Comment by 3LOK** [comment]
Done!
