### ISSUE TITLE
actions in finally{} block of forked task not captured

### ISSUE THREAD

**Issue by ixje** [wix/redux-saga-tester#38]
As said in the title, the `put` action in the `finally{}` block does not seem to get logged/captured. 

Example:

```
import { call, take, put, fork, cancel } from 'redux-saga/effects'
import { mockSaga } from 'redux-saga-mock'

function* forkAndAbort() {
    let forkedTask = yield fork(bgTask)
    yield take('ABORT')
    cancel(forkedTask)
    yield put({ type: 'THE_END' })
}

function* bgTask() {
    try {
        yield put({ type: 'BACKGROUND_SYNC_STARTING' })
        while (true) {
            yield setTimeout(function() {
                // NOP
            }, 1000)
        }
    } finally {
        if (yield cancelled()) {
            yield put({ type: 'BACKGROUND_SYNC_STOPPED' })
        }
    }
}

it("should capture the `BACKGROUND_SYNC_STOPPED` action but it doesn't", async () => {
    const sagaTester = new SagaTester({
        initialState: {}
    })

    sagaTester.start(forkAndAbort)
    sagaTester.dispatch({ type: 'ABORT' })
    await sagaTester.waitFor('THE_END')
    console.log(sagaTester.getCalledActions())
})

```

Output:

> console.log __tests__/wut.js:35
>     [ { type: 'BACKGROUND_SYNC_STARTING' },
>       { type: 'ABORT' },
>       { type: 'THE_END' } ]

I tried actually waiting for `BACKGROUND_SYNC_STOPPED` but that results in a timeout. 

I have a very similar construction in my application (replace the setTimeout with a `race`). That code is functional, stops the background task and dispatches the final `put` as expected.

**Comment by jonathanadler** [comment]
@ixje 
Are you sure you even enter the finally clause?
Try adding a log inside the finally clause before the if block.
I've tried your demo code, and even though redux-saga's docs says that the cancel effect should send the task to the finally clause, it seems that it's not happening.
And so, that's why the action was not captured; There was no action.

**Comment by PestoP** [comment]
Maybe it's just that you forgot to import `cancelled` from `redux-saga`. I got a 'silent' error like this last time.
And yes, I know, 4 years too late...
