### ISSUE TITLE
Does it work with AXIOS?

### ISSUE THREAD

**Issue by crazy4groovy** [wix/redux-saga-tester#39]
I've been struggling with this all day. Axios calls always return a non-status networking error inside the saga test. (I'm calling a json-server mock API)

Then I found this comment: https://github.com/wix/redux-saga-tester/issues/12#issuecomment-275197449

Is it true, Axios isn't compatible with saga tester?

If not, is `nock`ing the only way to test? (other than switching to fetch)

[nock test example](https://github.com/wix/redux-saga-tester/blob/master/examples/example.nock.js)

**Comment by crazy4groovy** [comment]
Thanks for your suggestion @jkomusin, neat stuff out there.

I'd like to keep testing with my json-server mock service, instead of hard-coding nock/mock reply bodies. (Makes successive API calls easier to test.) Luckily my API is fairly CRUD-like.

For the moment I'm switching to `fetch` with more success (some saga tests passing!), but still some strange xhr error results from GET requests with headers (?!?) Digging deeper...

**Comment by crazy4groovy** [comment]
Turns out, I'm seeing a network response error in my tests if I add an `Authentication` header to the request. Does that make any sense?

**Comment by 3LOK** [comment]
Hi - it seems axios doesn't work with nock. However, nock isn't required for redux-saga-tester, it's just something we use here.
See: [this](https://github.com/axios/axios/issues/305) for more information about axios + nock.
