### ISSUE TITLE
Testing sagas with delay

### ISSUE THREAD

**Issue by vovagusarov** [wix/redux-saga-tester#4]
Trying to test saga with delay, but it never goes to ```done()```. Example saga code took from your usage example and can be reproduced there:

```JavaScript
function* listenAndFetch() {
    yield call(delay, 200);
    yield take(fetchRequestActionType);
    const result = yield call(fetchApi);
    yield put({ type : fetchSuccessActionType, payload : result });
}
```

**Comment by bstro** [comment]
@3LOK Wondering if you have a solution for the above question. I am also running into this and I suspect you have also. Could you shed any light on how to advance a saga past a delay with your library?

**Comment by 3LOK** [comment]
Hi,

Not so sure I understand what's the problem, it works for me.

 Here's an example of a saga with delay, and its test:

DeleteSaga.js
```javascript

function* onDelete(clients, action) {

    const {itemIdx} = action.payload;

    yield put(SessionActions.actions.screenAreYouSure());

    const answer = yield take([
        DeleteActions.types.ARE_YOU_SURE_NO, 
        DeleteActions.types.ARE_YOU_SURE_YES
    ]);

    if (answer.type === DeleteActions.types.ARE_YOU_SURE_NO) {
        yield call(delay, 500)
        yield put(SessionActions.actions.screenList());
        return;
    }
    ...
    ...
}
```

DeleteSaga.test.js (note the async/await).
```javascript
    it.only('should return to main screen when users selects "no" in the yes/no screen', async () => {
        // User pressed delete
        sagaTester.dispatch(DeleteActions.actions.request({itemIdx:1}));

        // screen should be 'yes/no'
        expect(sagaTester.getLastActionCalled()).to.deep.equal([SessionActions.actions.screenAreYouSure()]); 

        // user presses 'no'
        sagaTester.dispatch(DeleteActions.actions.areYouSureNo());
        
        await sagaTester.waitFor(SessionActions.types.SCREEN_LIST);

        // screen should be main screen ('list')
        expect(sagaTester.getLastActionCalled()).to.deep.equal([SessionActions.actions.screenList()]); 
    });
```

However, I'll be honest, I think you should muck the delay function in case of a test to make your tests run faster.

**Comment by vovagusarov** [comment]
@3LOK, if you try your own example from readme, with a delay (as I described in my first comment) you will understand what I mean.
Yes, it should be mocked for tests, I agree, but I assume it should work without being mocked too.

**Comment by 3LOK** [comment]
So I've tested it, just like you said, and it worked perfectly. Added it to example.js.

Having said that, I decided to update the README and the example.js with async/await (I like this syntax better than standard promises). But delay still worked even with the previous version (with the promises).

If you want to check it out: copy example.js to the test directory, change its name to example.spec.js, and run 'npm test'.

Also added the new getLastActionCalled.

**Comment by vovagusarov** [comment]
I've seen your changes to example.js, but it's not really what I'm trying to do.
I use delay for debouncing, took the following code from saga documentation for reference:
```JavaScript
function* handleInput({ input }) {
  // debounce by 500ms
  yield call(delay, 500)
  ...
}

function* watchInput() {
  // will cancel current running handleInput task
  yield takeLatest('INPUT_CHANGED', handleInput);
}
```
In this case, when delay placed to the top of saga it doesn't work.
Thanks

**Comment by 3LOK** [comment]
@vovagusarov I've added an example called ```examples/example.debounce.js```. It works for me.

(to test it, copy to the test directory, rename to example.debounce.spec.js, and run ```npm test```

**Comment by vovagusarov** [comment]
@3LOK Did you push ```example.debounce.js``` ? Can't see it.

**Comment by 3LOK** [comment]
Sorry, pushed now: https://github.com/wix/redux-saga-tester/blob/master/examples/example.debounce.js

**Comment by vovagusarov** [comment]
Sorry, found an issue on my end.
Think we can close it, thanks for your help!

**Comment by einarq** [comment]
How would you go about doing this now that the delay function is provided by redux-saga out of the box?

Instead of this:
yield call(delay, 500)

We now have this:
yield delay(500);

**Comment by 3LOK** [comment]
Should still work, as expected. delay(500) just returns a promise, yield waits for.

I would still mock the delay function for faster run.

**Comment by radiosilence** [comment]
@3LOK How would one go about mocking the delay function? I have some code to retry requests with delays, and would like to do a full saga test but have the delay be 0ms always.
