### ISSUE TITLE
Running multiple sagas in test: *XXXX was waited for but never called* 

### ISSUE THREAD

**Issue by tvedtorama** [wix/redux-saga-tester#50]
Hi,

I run two sagas in a test, starting a wait for a future action before starting the first saga.   The second saga should raise/put the action, but not the first. 

This has been working so far, but now it gets rejected when the first saga completes.

This seems to be some new verify-logic, rejecting all pending waits when a saga exits.  This does not work well with multiple sagas, however, like in my case.

Is there a requirement that only a single saga is tested in each test?  Could you add an option to not reject the wait?

**Comment by InterAl** [comment]
@tvedtorama - how exactly do you run the 2 sagas? "start" accepts a single generator function.
