### ISSUE TITLE
Testing a saga dispatching actions handled by another saga

### ISSUE THREAD

**Issue by pgayvallet** [wix/redux-saga-tester#54]
Hello,

I'm trying to test a saga dispatching actions handled by another saga, and I can't seem to find how to make this work.

Tested saga

```
export function* initialize(action) {

    yield put(actions.loadingStart())

    // load & wait config
    yield put(configAccessor.fetch()) // <- this fire a FETCH action handled by datastoreSaga
    yield call(waitForState, configAccessor.isLoaded)
   ....
}
```

and the second : 

```
function* datastoreSaga() {
    yield takeEvery(types.FETCH, fetchData);
    yield takeEvery(types.REFRESH, refreshData);
}
```

I tryed to simply

```
sagaTester.start(datastoreSaga);
sagaTester.start(initialize);
```

But that doesnt work, the `datastoreSaga`'s `takeEvery(types.FETCH)` never calls it's `fetchData` saga.

Is it possible to test that kind of scenario ?

**Comment by MartinCerny-awin** [comment]
Are you calling it correctly? Is the fetch function action?

I am doing this and it works:

Tested saga
`yield put(patientActions.fetchPatientPartners());`

Patient actions
```const fetchPatientPartners = () => ({
  type: types.PATIENT_FETCH_PATIENT_PARTNERS_REQUEST,
});```

Second saga
```
function* fetchPatientPartnersRequest() {
  try {
    const res = yield call(api.get, '/patientPractices');
  } 
}

function* watchPatientRequests() {
  yield takeLatest(types.PATIENT_FETCH_PATIENT_PARTNERS_REQUEST, fetchPatientPartnersRequest);
}
```

I do not have to start second saga. I just need to start the first one.

**Comment by InterAl** [comment]
@pgayvallet sagaTester.start takes a single saga (a generator function). You can spawn additional sagas from your root sagas. This pattern is similar to redux's reducers.

See here for additional information: https://redux-saga.js.org/docs/api/#middlewarerunsaga-args
