### ISSUE TITLE
Not Compatible with Redux-Saga 1.0.0

### ISSUE THREAD

**Issue by framerate** [wix/redux-saga-tester#57]
If this is still maintained, I did the initial work (but tests are failing) here:

https://github.com/OpenPathSec/redux-saga-tester/commit/14810d144674629c0f71b0eaf328d2d23aa08fef

Let me know the status of this project (and maybe some help with the first test which seems a little awkward) and I can assist further and get this up to date!

**Comment by tibbus** [comment]
Nice work @framerate , I have this issue as well, I hope this is still maintained.

**Comment by framerate** [comment]
I haven't had a chance to make the tests pass but if you want to help tag
team it we can get a PR and if this isn't maintained I can petition npm to
move ownership to me

**Comment by ywongweb** [comment]
Thanks @framerate

**Comment by Levino** [comment]
What about this PR https://github.com/wix/redux-saga-tester/pull/45/files

**Comment by jeremy-deutsch** [comment]
Hey y'all, I just hopped on the PR train with [my own PR.](https://github.com/wix/redux-saga-tester/pull/59) It has the same changes as above, but passes all tests, and should be compatible with both pre-1.0 and post-1.0 redux-saga (runs tests on both). :smiley:

**Comment by bramski** [comment]
Not sure what's up and why Wix hasn't touched this repo but I've emailed their engineering team to try and get some new maintainers.

**Comment by bramski** [comment]
@jeremy-deutsch Can you add the dist/SagaTester.js to your repo? Or change the package.json so that your PR is installable?
