### ISSUE TITLE
Maintenance??!

### ISSUE THREAD

**Issue by Levino** [wix/redux-saga-tester#58]
No commits since January 2018. Could someone please quickly elaborate on the status of maintenance?

**Comment by k-funk** [comment]
Would also like to know what's up here, I've been using this library and am concerned that I'm gonna have to rewrite hundreds of tests if this doesn't get maintained by someone... and forking is never the nicest solution.

**Comment by InterAl** [comment]
Status of maintenance: active. We welcome PRs.
