### ISSUE TITLE
.done undefined, (cannot read property 'then' of undefined)

### ISSUE THREAD

**Issue by bramski** [wix/redux-saga-tester#60]
Reopening https://github.com/wix/redux-saga-tester/issues/56

I'm having this problem across all of my saga tests after upgrading to redux-saga 1.0.0 and redux-saga-tester 1.0.406.

**Comment by bramski** [comment]
Related to: https://github.com/wix/redux-saga-tester/issues/57

**Comment by InterAl** [comment]
Fixed in #59
