### ISSUE TITLE
Wait for multiple actions

### ISSUE THREAD

**Issue by thijssteel** [wix/redux-saga-tester#63]
Currently, we can wait for a succes action via
`await sagaTester.waitFor(SUCCES)`
However, when something fails, it results in a FAILURE action being thrown and even though the test fails, it does so because the SUCCES action was never dispatched. The test could be fail faster by listening for either a SUCCES of FAILURE action and later check that it was in fact a SUCCES action.

To this end, would it be possible to have the waitFor function accept and array of action types?

**Comment by InterAl** [comment]
I think Promise.race delivers what you desire:
```
await Promise.race([sagaTester.waitFor(SUCCESS), sagaTester.waitFor(FAILURE)])
```
