### ISSUE TITLE
Filtering out '@@redux' actions prevents inspection of redux-form actions

### ISSUE THREAD

**Issue by jkomusin** [wix/redux-saga-tester#7]
The filtering of actions starting with '@@redux' prevents [redux-form's action types](https://github.com/erikras/redux-form/blob/master/src/actionTypes.js) from being captured, as they all start with '@@redux-form'.

More than happy to discuss and PR a removal or a flag to optionally filter them 😃

**Comment by 3LOK** [comment]
Hey @jkmusin

Feel free to PR a flag. I'd suggest the defaul of the flag will be "filtered out" so as to be backwards compatible. 

Tag me on the PR and I'll merge immediately.

**Comment by 3LOK** [comment]
Merged, and closed.
